### PR TITLE
Add more variations and console keymaps

### PR DESCRIPTION
**Pull request by noctuid**
This pull request is not ready to be accepted, but I thought I would get some feedback before working on it more. I still need to make a few formatting changes, double check that there aren't any errors in the keymaps, and output the keymap files to top-level folders. Right now, I haven't overwritten the existing xmodmap files. I can add a Makefile to install the console keymap files as well.

The keymap files were generated with a script from a base file and headers and footers. I can remove these files if you only want the keymap files in the repo, but I think they are potentially nice since a change in the base file can quickly be applied to all the keymap files.

Is the formatting of the new keymap files okay? I tried to keep them pretty much the same as the current ones. The main difference is that the columns are left justified. I also wanted to ask about the naming of the variations of the angle mod. For ANSI, I called the normal one "z" and alternate one "shift-z." I also added the version that keeps z in the same position and shifts keys over to the right, calling it "keep-z." I'll add whatever names you think are best to the first line in each keymap file (along with "Wide", "left-hand only", etc.).

I can also add wide mods for the "z" and "shift-z" angle mods and make any other changes you want.

### CODE REVIEW

**Comment by stevep99** [comment]
Great, thanks for your work on this! 

I don't have any strong opinions on formatting, the files look fine to me. I agree that having the generated files in the repo is good as some people might not want to run the script.

I'm not an expert on console keymap files to spot any potential issues, but I offer the following suggestions, esp regarding the "generate" script, so make it more user-friendly to new users:

1. Can you have it so that running the generate command without arguments prints some kind of help/usage message.
2. Can you put in a check to see if sponge is installed - and if it's missing the script should exit gracefully.
3. The "generate" folder might be better named something more specific, maybe "generate-linux-keymaps" or something, so that's it's unambiguously clear what's in there. 

I tried setting a console keymap but it failed due to not finding "qwerty-layout". I don't know if that's just because my setup is a bit non-standard though?

Otherwise looking good. With those little bits of extra finesse on the script, I'd be happy to merge.

**Comment by noctuid** [comment]
Yes I'll add some help information, ensure that sponge is installed, and make the naming more explicit.

I actually just used the official console colemak keymap from my system (`/usr/share/kbd/keymaps/i386/colemak/colemak.map.gz`) as a reference which has `include "qwerty-layout"`. I'll need to look into this more I guess. Could you give me the colemak keymap file from your system?

Also, would it be okay to add keymaps for @DreymaR's DbgHk variant? Doing that would double the number of keymaps, so it would probably be better to split the variants into folders.

**Comment by stevep99** [comment]
OK great.

I found the keymaps, on my system they seem to be in /usr/share/keymaps/i386 (i.e. without the "kbd" directory).

I was able to get the console keymap to work, however on my system it complained about specific entries in the mapping file (examples were EuroSign, leftsinglequotemark, dead_abovering). But once I had replaced the entries it complained about, all worked fine. Good to have Mod-DH on the console, you never know when X might fail to boot for osme reason!  No idea why those names were not recognised, perhaps some are not supported on all systems?

(I was using Ubuntu 16.04 for this test.)

Feel free if you want to add DreymaR's variant, or any other variant come to that. I noticed you have also added the left-only versions, I am actually not that bothered about those - I was thinking of maybe deprecating them as I don't know of anyone who has applied the left mod only - but you can leave them if you prefer.

**Comment by noctuid** [comment]
I added help flags (`-h` and `--help`). The help message will also be printed if invalid flags are used. Running it without arguments will still generate the keymaps (hopefully that is fine).

I made the other suggested changes, added DbgHk keymaps, and added wide versions of the "z" and "shift z" ansi keymaps. I renamed the other wide mod to awing.

I made the left variants optional (generated with `l` or `--left`) and took them out.

> on my system they seem to be in /usr/share/keymaps/i386

Yes, it looks like that's the location for Debian-based distros. I added a Makefile with this as the default install location.

> however on my system it complained about specific entries in the mapping file

Yes, these needed to be changed. They were in the original colemak keymap file, but they were commented (so before testing I wasn't sure if they would work or not). When you tested the keymaps did they still work with `include "qwerty-layout"`?

For the shift z angle mod, is there a specific key that should be in the bottom middle? Since it was blank in [the example](https://colemakmods.github.io/mod-dh/gfx/mod_dh_keyb_ansi_shiftz.png), I just left it as alt.

I'll check over the files again to make sure I didn't mess anything up later when I get the chance.

**Comment by stevep99** [comment]
That all sounds good to me.

The bottom middle key in [that example](https://colemakmods.github.io/mod-dh/gfx/mod_dh_keyb_ansi_shiftz.png) is left blank as I don't know what people would want to do in this case. Your suggestion of Alt makes sense though.

Yeah, in my test I did the get it to set the console successfully (once I'd replaced those unrecognised characters) so I presume it must have found the "qwerty-layout" dependency OK.

Give me the nod whenever you're happy with it and I'll hit the merge button.

**Comment by noctuid** [comment]
Okay, I fixed a few minor issues. It should be good now.

**Comment by stevep99** [comment]
Nice, sounds good.
Looking at the commits for the pull request, I am only seeing one ( Jan 18)
currently.
Have you pushed up all your latest changes, or am I misreading something
it?

**Comment by stevep99** [comment]
OK I see, it is a merged commit. Hadn't realized that was possible.

**Pull request merged**
