### PR TITLE
Overhaul macOS Colemak DH implementation.

### PR DESCRIPTION
**Pull request by njdoyle**
Here's the overhaul of macOS Colemak DH and Colemak DHk support.

There's a bundle for `Colemak DH` and a bundle for `Colemak DHk`. Each bundle has support for ANSI and ISO angle fingering as well as Matrix fingering. For each fingering, there's a normal variant and the "Extended" deadkeys variant based on the built-in "ABC" and "ABC - Extended" keyboard layouts.

### CODE REVIEW

**Comment by ranelpadon** [comment]
@njdoyle Thanks for your effort on this, commendable work indeed. And it's good that you updated as well the `macOS` `README.md` and the `macOS` download link in the main `README`.

Some clarifications/suggestions:
1. Logging-out of the current session and logging-in back will work too and it's much quicker:
> After installation, you may need to reboot your system for the keyboard layout to become available in your System Preferences.

2. Shouldn't we retain the reference to `Ukelele`? This is in the original `README` contents. On my case, this is helpful since I didn't know about `Ukelele` and it made me possible to edit the `Alt`/`Alt+Shift` keys as well for remapping punctuation in the **Colemak DH** layout, mainly for programming needs. Maybe need some rephrasing as well:
```## To customize
Download a copy of the SIL.org Ukelele tool from http://scripts.sil.org/ukelele. 
You should be able to open the bundle and start editing. 
```

3. This is the appearance in the macOS toolbar, I'm in Dark Mode, is this intended? Also, note that the original icon shows **DH** icon (Colemak-DH) not **CO** (Colemak), not sure if it's big deal, but personally I like the **DH** one to differentiate it from the vanilla Colemak which is pre-installed in Mac.
toolbar

4. FYI, I have installed the bundles in my Mac, and it looks ok. I've also updated my **[Keyzen Colemak-DH](https://ranelpadon.github.io/keyzen-colemak-dh/)** site/project which includes now the updated layout/sequences/images: `colemak-dh`, ` colemak-dhk`, ` colemak-dh-matrix`, ` colemak-dhk-matrix`. The layout images in that site are the screenshots from my Mac also, so will be helpful for validating the changes in this PR. Didn't include the ISO/Extended variants though in my project to minimize clutter.

CC: @stevep99 @DreymaR @BenDover178

**Comment by njdoyle** [comment]
These are all good points!

1. I'm happy to make this change. I was under the impression that a full reboot was necessary but on further reflection I probably confused/convolved this with my experience the first time installing a third-party layout user-local and encountering the sensitive input restrictions.
2. I'll add the reference to Ukelele.
3. I actually spent a few hours trying to get the same behaviour as the system keylayout icons that change colours with light/dark modes but couldn't figure it out. The icon is the same icns data that is used for the build-in Colemak layout. For some reason it isn't using the mask variation like I would expect. I learned the icns format and whipped out my hex editor and everything. I gave up trying to get it to work and settled for what you see here. I'll make a new icon that will work in both light and dark mode (though won't change colour). If you know how to imitate the system behaviour, I'd love to know the details.
4. The more verification that can be done the better. :)

I'll update the PR when I get some time to make the changes tomorrow.

**Comment by njdoyle** [comment]
I've updated with the suggested changes to the readme and new icons.

I spent more time trying to figure out how to get dynamic icons for light/dark mode but still couldn't get it. I need to indicate — somehow — that my icons are "template images" but I can't find any way to indicate that. The macOS built-in layouts are all in some binary undocumented format and it wasn't obvious how to do what I want with some surface-level investigation there. So, for now, I made new icons that will display with appropriate contrast in both light and dark mode.

What do you all think?

**Comment by BenDover178** [comment]
I wouldn't worry too much about the icon; if it's clear in both light/dark mode that should be good enough (then again, I'm not really picky about desktop visuals).

**Comment by ranelpadon** [comment]
@njdoyle 

Checked your changes:
- the logout/login is now indicated in README
- the `Ukelele` is now indicated in README
- reinstalled your bundle to verify the changes in Mac, the icons look much better now compared to you earlier version! And good idea to have separate `DH` and `DHk` icons. Likewise, it looks good both for Dark and Light themes:
Screen Shot 2020-11-01 at 3 27 06 PM

Screen Shot 2020-11-01 at 3 27 44 PM

Screen Shot 2020-11-01 at 3 38 55 PM

Screen Shot 2020-11-01 at 3 42 42 PM

Thanks a lot for your ideas/effort! @stevep99 I think this is good candidate now for merging, unless you have other concerns. :)

**Comment by stevep99** [comment]
Great. Nice work on this guys, merging.

**Pull request merged**
