### PR TITLE
Direct users to kbd project for Linux console keymaps

### PR DESCRIPTION
**Pull request by cal-andrew**
The [kbd project](https://kbd-project.org/) contains Linux console keymaps, among other things, and comes by default as part of most Linux distributions.

I recently submitted a patch to make Caps Lock the default, not knowing that their [Colemak-DH console keymaps](https://git.kernel.org/pub/scm/linux/kernel/git/legion/kbd.git/tree/data/keymaps/i386/colemak) were originally copied from the console folder here (I have submitted another patch to bring it up to date with changes here).

I think removing the console keymap files here and directing people to the kbd project would help both users (by informing them it's probably already on their distribution) and developers (by there being a single location to view and modify Linux console keymaps).

### CODE REVIEW

**Comment by cal-andrew** [comment]
I guess the big downside would be that it would be harder to modify the layout so I'm not sure if the benefits would outweigh that.

**Comment by stevep99** [comment]
I didn't know the console files had been added to kbd probject.  I agree it's probably a better place for them than here. Have you got a link to your proposed patch bringing them up to date?

**Comment by cal-andrew** [comment]
Here is a link: https://lore.kernel.org/kbd/20240928095328.23259-1-contact@candrew.net/T/#u
I will post here when it gets merged.

**Comment by cal-andrew** [comment]
The patch has been applied now: https://git.kernel.org/pub/scm/linux/kernel/git/legion/kbd.git/commit/?id=21b3a3a43cf6372dbf6632295f81f4666c9c88e9

**Pull request merged**
